In [2]:
from __future__ import print_function
import six
import os  # needed navigate the system to get the input data
import SimpleITK as sitk
import radiomics
from radiomics import featureextractor  # This module is used for interaction with pyradiomics
import nibabel as nib
import nrrd
import numpy as np

In [3]:
# Get the testCase
imagePath = '/media/lhj/Disk/qianlong/test_data/data/pat001/fa.nrrd'
maskPath = '/media/lhj/Disk/qianlong/test_data/data/pat001/pat001_mask.nii'
para_name = '/media/lhj/Disk/qianlong/Script/feature_benchmark/Radiomics_FenKai/Radiomics_FenKai/MR_MAGiC.yaml'
# img = nib.load(maskPath)
# print(img)
# img1 = nrrd.read(imagePath)
# print(img1)
# img_affine  = img.affine
# img = img.get_data()
itk_img = sitk.ReadImage(maskPath)
img = sitk.GetArrayFromImage(itk_img)
img = np.transpose(img,(1,2,0))
print(img.shape)
filename = '/media/lhj/Disk/qianlong/test_data/data/pat001/mask.nrrd'
# # Write to a NRRD file
nrrd.write(filename, img)
# Instantiate the extractor
extractor = featureextractor.RadiomicsFeatureExtractor()
# radiomics.featureextractor.RadiomicsFeatureExtractor(para_name)
result = extractor.execute(imagePath, filename)
print(result)

(256, 256, 16)


ValueError: Image/Mask geometry mismatch. Potential fix: increase tolerance using geometryTolerance, see Documentation:Usage:Customizing the Extraction:Settings:geometryTolerance for more information

In [19]:
maskPath = '/media/lhj/Disk/qianlong/test_data/data/pat001/pat001_mask.nii'
faPath = '/media/lhj/Disk/qianlong/test_data/data/pat001/faa.nii'
itk_img = sitk.ReadImage(faPath)
# print(itk_img)
img = sitk.GetArrayFromImage(itk_img)#这里主要是为了读取nii原图像array然后索引单张dicom，对每张图像添加header信息
print(img)
pixel = itk_img.GetMetaData('pixdim[1]')

[[[-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]
  ...
  [-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]]

 [[-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]
  ...
  [-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]]

 [[-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]
  ...
  [-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]]

 ...

 [[-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]
  ...
  [-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]
  [-256 -256 -256 ... -256 -256 -256]]

 [[-256 -256 -256 ... -256 -256 -256]
  [-256 -256